### ISSUE TITLE
Some ideas for improvemnent

### ISSUE THREAD

**Issue by btd** [aMarCruz/rollup-plugin-pug#4]
Hi, there - great work!

I have tried this plugin and would like to suggest some ideas for improvement:
1. You have runtime as CJS - i am suggesting to convert this to modules
2. You check if need to add runtime by regexp searching (i know it is best possible way now - because of pug code gen module). I suggest there to use regexp to replace `pug.method` names while collecting them for es6 import.
You can generate regexp something like  `Object.keys(require('pug-runtime')).map(m => 'pug\\.'+m).join('|')`, so while doing string.replacing you can guther all used methods and include in moduels import only in use.

What do you think? I can create PR if you do not have time.

**Comment by aMarCruz** [comment]
@btd at this point, I don't think granularizing the runtime is convenient because:

a) Pug 2.x is still in beta yet, so the runtime code is unstable. Wrapping it is a more secure way of exposing this and future 2.0 versions to rollup that replacing the internal declarations.

b) Minified, the runtime is 2k only. It is not significant in any application and the risk of a bad replacement in the code generated by Pug is high.

...even more, I don't remember why the replacement in the [line# 91](https://github.com/aMarCruz/rollup-plugin-pug/blob/9ea32faf885d5c67847712ff82e533fc7a20f0ce/src/index.js#L91) but it was stupid :S

Anyway, thanks for your feedback.

PS
I have not had time to enhance this plugin with async operation (currently we are working w/ brunch), which is a feature that I would like to include ...do you? PR is welcome.
